package InterfaceGrafica.adm;
import InterfaceGrafica.jfPrincipal;
import Pessoa.Adm;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

public class jfMenuAdm extends javax.swing.JFrame{
    private Adm admRei;
    //salvando arquivo    
    public static void gravarArquivo(Adm adm)
            throws IOException {
        ObjectOutputStream arquivo =
                new ObjectOutputStream(
                        new FileOutputStream("backup.dat")
                );

        arquivo.writeObject(adm);
        arquivo.close();
    }
    //recuperando arquivo
    public static Adm lerArquivo()
            throws IOException, ClassNotFoundException {
        Adm novo;

        ObjectInputStream arquivo =
                new ObjectInputStream(
                        new FileInputStream("backup.dat")
                );
        
        novo = (Adm) arquivo.readObject();
        arquivo.close();
        return novo;
    }
    
    
    
    /**
     * Creates new form jfMenuAdm
     */
    public jfMenuAdm() {
        initComponents();
        //resgatando informacoes do arquivo
        try {
            admRei = lerArquivo();
        }catch(ClassNotFoundException e){
            System.out.println("Erro ;-;");
        }catch(IOException e){
            System.out.println("Erro ao tentar ler arquivo");
        }
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntLogoutAdm = new javax.swing.JButton();
        bntCriarCoord = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU ADM");

        bntLogoutAdm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntLogoutAdm.setText("Logout ");
        bntLogoutAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLogoutAdmActionPerformed(evt);
            }
        });

        bntCriarCoord.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bntCriarCoord.setText("Criar Coordenador");
        bntCriarCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCriarCoordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(bntCriarCoord)))
                .addContainerGap(149, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(bntLogoutAdm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addComponent(bntCriarCoord)
                .addGap(18, 18, 18)
                .addComponent(bntLogoutAdm)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntLogoutAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLogoutAdmActionPerformed
        // TODO add your handling code here:
        jfPrincipal logout = new jfPrincipal();
        dispose();
        logout.setVisible(true);
    }//GEN-LAST:event_bntLogoutAdmActionPerformed

    private void bntCriarCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCriarCoordActionPerformed
        // TODO add your handling code here:
        jfCriandoCoord tlCriarCoord = new jfCriandoCoord();
        dispose();
        tlCriarCoord.setVisible(true);
    }//GEN-LAST:event_bntCriarCoordActionPerformed

    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new jfMenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCriarCoord;
    private javax.swing.JButton bntLogoutAdm;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
